In [1]:
from qutip import *
import numpy as np
from TK_basics import *
import TK_basics as tk
from helper_functions import *
import importlib
importlib.reload(tk)
import src.encoding.evolution as evolution
importlib.reload(evolution)
from src.encoding.evolution import Evolve

In [95]:
import src.encoding.evolution as evolution
importlib.reload(evolution)
from src.encoding.evolution import Evolve
img = np.array([0.19031461653056986, -0.5433694189241283, 0.941050527248425, 0.4814215388610822, 0.5052590530838083,
                    -0.4881473132004496, 0.18178470184430385, -0.35487379853721646, 0.5686678766949724,
                    0.36226119031810744, 0.1553727142224298, -0.6545945224962656, -0.2925330621674876, 0.1809035742188693,
                    0.59519396673181, -0.1256754626669716])
#e = Evolve(img, measurement='pns trace', cdim=15, dm=10, t_total=2e-6, anharm=True, c_ops=True,
                      #ffilter=True, intervals=1, nsteps=10000, pc_real=1.1e6, pq_real=1.1e6)
#p = e.vector()

In [184]:
rho_i = e.rho_test()[:14,:14]


In [185]:
p_i = np.hstack([list(rho_i[:, i].T) for i in range(14)])

In [186]:
p_i

array([ 3.62608849e-01-1.05980236e-16j,  9.03043504e-02-1.04185927e-01j,
       -4.49484625e-02-6.40648297e-03j, -3.18778406e-02+9.24628170e-02j,
        4.83871646e-02+7.02121904e-02j,  1.04275840e-01-2.20103205e-02j,
        9.82048793e-02-8.38123425e-02j,  3.03262056e-02-9.40419374e-02j,
       -3.83765434e-02-8.40869425e-02j, -6.00442977e-02-6.10055282e-02j,
       -5.05210816e-02-8.02485010e-03j, -3.40084354e-02+3.10074715e-02j,
       -9.96493113e-03+1.67103524e-02j,  2.97906342e-03+1.32747547e-02j,
        9.03043504e-02+1.04185927e-01j,  1.15757807e-01-6.60366235e-17j,
        5.96207834e-02-6.88761829e-03j, -3.72791508e-02+4.74329664e-02j,
       -4.43165349e-02+3.84496822e-02j,  1.90498986e-03+4.59792134e-04j,
        6.39880069e-02+2.28590082e-04j,  5.69366305e-02+2.28428227e-02j,
        7.52077120e-03-6.05985176e-03j, -8.33488897e-03-6.20828527e-02j,
       -3.14627210e-04-2.64780906e-02j, -6.12846900e-03+2.29604743e-02j,
       -6.10985204e-03-1.59086048e-02j, -7.46783046

In [188]:
displacements = np.load('..\\data\\pns_disps10.npy')
E = []
cdim=54
proj = fock_dm(cdim, 9)
for alpha in displacements:
    D = displace(cdim, alpha)
    E.append(np.hstack(D.dag()*proj*D)[0])
E = np.array(E)

In [171]:
E@rho_vec.T

array([0.01448663-2.49800181e-16j, 0.02153258+6.93889390e-17j,
       0.087353  -8.32667268e-17j, 0.0463886 -9.71445147e-17j,
       0.00616006-1.66533454e-16j, 0.0273283 -3.33066907e-16j,
       0.11549818-1.24900090e-16j, 0.09628068-1.11022302e-16j,
       0.04806525+2.28983499e-16j, 0.01448349-5.55111512e-17j,
       0.0913876 -8.32667268e-17j, 0.01051598+4.02455846e-16j,
       0.09331316-7.21644966e-16j, 0.09653728+1.11022302e-16j,
       0.0399845 +2.08166817e-17j, 0.04924833-4.51028104e-16j,
       0.01994849-1.04083409e-16j, 0.13434481+1.66533454e-16j,
       0.01362026+2.42861287e-16j, 0.0047979 +2.70616862e-16j,
       0.02023445+1.38777878e-17j, 0.05513536+3.33066907e-16j,
       0.02470612-1.66533454e-16j, 0.01052902-2.77555756e-17j,
       0.04463727+2.55004351e-16j, 0.00926602+1.11022302e-16j,
       0.02493636+7.63278329e-17j, 0.0539592 +5.55111512e-17j,
       0.03782573+5.55111512e-17j, 0.00570448+2.91433544e-16j,
       0.04712212+3.33066907e-16j, 0.02925208-1.2490009

In [189]:
E@(p_i.T)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 196 is different from 2916)

In [174]:
p

array([0.01448663, 0.02153258, 0.087353  , 0.0463886 , 0.00616006,
       0.0273283 , 0.11549818, 0.09628068, 0.04806525, 0.01448349,
       0.0913876 , 0.01051598, 0.09331316, 0.09653728, 0.0399845 ,
       0.04924833, 0.01994849, 0.13434481, 0.01362026, 0.0047979 ,
       0.02023445, 0.05513536, 0.02470612, 0.01052902, 0.04463727,
       0.00926602, 0.02493636, 0.0539592 , 0.03782573, 0.00570448,
       0.04712212, 0.02925208, 0.039104  , 0.01590352, 0.05236333,
       0.0666793 , 0.03548897, 0.01423548, 0.08540541, 0.0253576 ,
       0.0745645 , 0.14158174, 0.03469367, 0.00981494, 0.04088812,
       0.03640471, 0.06581602, 0.03222873, 0.0635727 , 0.01459915,
       0.01753917, 0.04221993, 0.03816966, 0.05638922, 0.00963694,
       0.01480548, 0.03424332, 0.15847097, 0.05933325, 0.12131209,
       0.01727695, 0.03355315, 0.05844377, 0.04257261, 0.0106373 ,
       0.02417825, 0.06112309, 0.05042623, 0.05928255, 0.04757814,
       0.06620505, 0.01263266, 0.02101241, 0.0257023 , 0.06029

In [179]:
rho_vec

array([ 0.10412235+9.42167040e-18j,  0.02391765-4.14962740e-02j,
       -0.00728839-1.28478362e-02j,  0.00557723+2.92301971e-02j,
        0.00378968-5.26435483e-03j,  0.02496239-2.08521546e-02j,
        0.03662599-3.64630250e-02j,  0.01934217-4.47602125e-02j,
        0.00097222-4.84017598e-02j,  0.01483178-3.50231355e-03j,
        0.02561465+5.52380993e-03j, -0.0356276 +2.70588664e-02j,
       -0.0450809 +2.12951888e-02j,  0.01403442+3.01382110e-03j,
        0.02794103-1.59957687e-02j,  0.02391765+4.14962740e-02j,
        0.10159505+1.02245356e-17j,  0.02440408+1.33465954e-02j,
       -0.00913654+6.40813822e-03j,  0.00326783+2.07320796e-02j,
        0.01549804+4.54543158e-03j,  0.05070638+1.00877068e-02j,
        0.06516521+1.64017411e-02j,  0.01726467-2.05569769e-02j,
       -0.0026693 -1.80445296e-02j, -0.00024189-1.35559880e-02j,
        0.01049841+5.46018993e-03j, -0.00018794-1.22073670e-02j,
       -0.01529502-1.34289386e-02j, -0.00964671+2.07454052e-02j,
       -0.00728839+1.2847

In [190]:
rho_vec = np.linalg.pinv(E)@p
rho = np.hstack([c[..., None] for c in np.split(rho_vec,cdim)])

In [191]:
Qobj(rho)

Quantum object: dims = [[54], [54]], shape = (54, 54), type = oper, isherm = True
Qobj data =
[[ 1.03455381e-01+7.72230250e-18j  9.41631987e-03+1.91281920e-02j
  -5.69849870e-03+7.99947985e-03j ...  1.14224891e-03-1.33832920e-04j
   8.32645667e-07+6.60321824e-04j  1.91666894e-05+3.12164924e-04j]
 [ 9.41631987e-03-1.91281920e-02j  8.78072748e-02-4.19602144e-18j
   1.38610351e-02+1.69002446e-02j ...  2.32684080e-03+1.45944039e-03j
   7.41977475e-04-3.09781241e-04j  8.80554153e-05+2.90960261e-03j]
 [-5.69849870e-03-7.99947985e-03j  1.38610351e-02-1.69002446e-02j
   5.65629529e-02+1.04957030e-17j ...  3.58733014e-03-3.83043172e-03j
   7.13237573e-04+4.80467918e-04j  2.73334487e-03+2.34304851e-03j]
 ...
 [ 1.14224891e-03+1.33832920e-04j  2.32684080e-03-1.45944039e-03j
   3.58733014e-03+3.83043172e-03j ...  7.17354682e-03+1.90991059e-19j
   5.74413102e-04+8.37850173e-04j  4.84011046e-04+5.44236981e-03j]
 [ 8.32645667e-07-6.60321824e-04j  7.41977475e-04+3.09781241e-04j
   7.13237573e-04-4.804

In [192]:
rho_i

array([[ 3.62608849e-01-1.05980236e-16j,  9.03043504e-02+1.04185927e-01j,
        -4.49484625e-02+6.40648297e-03j, -3.18778406e-02-9.24628170e-02j,
         4.83871646e-02-7.02121904e-02j,  1.04275840e-01+2.20103205e-02j,
         9.82048793e-02+8.38123425e-02j,  3.03262056e-02+9.40419374e-02j,
        -3.83765434e-02+8.40869425e-02j, -6.00442977e-02+6.10055282e-02j,
        -5.05210816e-02+8.02485010e-03j, -3.40084354e-02-3.10074715e-02j,
        -9.96493113e-03-1.67103524e-02j,  2.97906342e-03-1.32747547e-02j],
       [ 9.03043504e-02-1.04185927e-01j,  1.15757807e-01-6.60366235e-17j,
         5.96207834e-02+6.88761829e-03j, -3.72791508e-02-4.74329664e-02j,
        -4.43165349e-02-3.84496822e-02j,  1.90498986e-03-4.59792134e-04j,
         6.39880069e-02-2.28590082e-04j,  5.69366305e-02-2.28428227e-02j,
         7.52077120e-03+6.05985176e-03j, -8.33488897e-03+6.20828527e-02j,
        -3.14627210e-04+2.64780906e-02j, -6.12846900e-03-2.29604743e-02j,
        -6.10985204e-03+1.59086048e-0

In [142]:
fidelity(Qobj(rho_i[:10,:10]),Qobj(rho[:10,:10]))

0.6275245278500965

In [115]:

g = fock_dm(2, 0)

D = displace(15, displacements[1])

In [93]:
D*rho_i*D.dag()

Quantum object: dims = [[15], [15]], shape = (15, 15), type = oper, isherm = True
Qobj data =
[[ 0.06773493+0.j          0.06673337+0.05127076j  0.00578286+0.07518635j
  -0.05024883+0.03445524j -0.05251734-0.01815757j -0.01205419-0.02937972j
   0.02422971-0.00912176j  0.01976322+0.01397461j -0.0110445 +0.0238915j
  -0.02963591+0.00096832j -0.03870523-0.02130928j  0.00704945-0.03665387j
   0.01400667-0.05719278j  0.02782998+0.00094141j  0.0625792 +0.01275909j]
 [ 0.06673337-0.05127076j  0.1303789 +0.j          0.10158467+0.07117522j
   0.0255686 +0.05791265j -0.03250553-0.00380985j -0.04091293-0.03253225j
   0.00550947-0.01275929j  0.04075403+0.0102749j   0.00705815+0.02772053j
  -0.03025583+0.03375361j -0.0538278 +0.00292066j -0.02431923-0.04109916j
  -0.02959252-0.08278601j  0.03367734-0.00830207j  0.06237904-0.04371965j]
 [ 0.00578286-0.07518635j  0.10158467-0.07117522j  0.14767156+0.j
   0.11619278+0.03875475j  0.02907992+0.02000665j -0.04604007-0.00870848j
  -0.02810148-0.00592507j

In [95]:
t = tensor(g, rho_i).unit()
d = tensor(qeye(2), D)
(d*t*d.dag()).ptrace(1)[9,9]

(0.021532578733805333+0j)

# Testing

In [96]:
def r2v(r):
    l = r.shape[0]
    return np.hstack([list(r[:, i].T) for i in range(l)])[0]

def v2r(v):
    n = int(np.sqrt(len(v)))
    return Qobj(np.hstack([c[..., None] for c in np.split(v,n)]))

In [178]:
cdim = 15
d = 10
displacements = np.load('..\\data\\pns_disps10.npy')

In [179]:
e = Evolve(img, measurement='pns trace', cdim=15, dm=10, t_total=2e-6, anharm=True, c_ops=True,
                      ffilter=True, intervals=1, nsteps=10000, pc_real=1.1e6, pq_real=1.1e6)
e.vector()


array([0.01448663, 0.02153258, 0.087353  , 0.0463886 , 0.00616006,
       0.0273283 , 0.11549818, 0.09628068, 0.04806525, 0.01448349,
       0.0913876 , 0.01051598, 0.09331316, 0.09653728, 0.0399845 ,
       0.04924833, 0.01994849, 0.13434481, 0.01362026, 0.0047979 ,
       0.02023445, 0.05513536, 0.02470612, 0.01052902, 0.04463727,
       0.00926602, 0.02493636, 0.0539592 , 0.03782573, 0.00570448,
       0.04712212, 0.02925208, 0.039104  , 0.01590352, 0.05236333,
       0.0666793 , 0.03548897, 0.01423548, 0.08540541, 0.0253576 ,
       0.0745645 , 0.14158174, 0.03469367, 0.00981494, 0.04088812,
       0.03640471, 0.06581602, 0.03222873, 0.0635727 , 0.01459915,
       0.01753917, 0.04221993, 0.03816966, 0.05638922, 0.00963694,
       0.01480548, 0.03424332, 0.15847097, 0.05933325, 0.12131209,
       0.01727695, 0.03355315, 0.05844377, 0.04257261, 0.0106373 ,
       0.02417825, 0.06112309, 0.05042623, 0.05928255, 0.04757814,
       0.06620505, 0.01263266, 0.02101241, 0.0257023 , 0.06029

In [180]:
r_rand = e.rho_test()
p = []
proj = fock_dm(cdim, d-1)
for alpha in displacements:
    D = displace(cdim, alpha)
    p.append((proj*D*r_rand*D.dag()).tr())

In [181]:
E = []
for alpha in displacements:
    D = displace(cdim, alpha)
    E.append(np.hstack(D.dag()*proj*D)[0])
E = np.array(E)

In [182]:
p

[0.014486625179337175,
 0.021532578733804385,
 0.08735299594519338,
 0.04638860401417091,
 0.006160058895622975,
 0.027328303671678274,
 0.11549818152586468,
 0.09628068493035913,
 0.048065248477159116,
 0.014483490455357588,
 0.09138759811254042,
 0.010515979100342526,
 0.09331316331809843,
 0.09653727593396734,
 0.03998450338457373,
 0.04924832671430017,
 0.019948488316883756,
 0.13434481420838373,
 0.01362026263745423,
 0.004797899743504925,
 0.02023445062870537,
 0.05513535740133955,
 0.024706115403013405,
 0.010529017986125294,
 0.04463726820559992,
 0.009266020724907835,
 0.02493636124231409,
 0.05395919618642241,
 0.037825728667102994,
 0.005704484414897516,
 0.04712211624576286,
 0.029252080701916275,
 0.03910399607501029,
 0.01590352046163766,
 0.05236332512310424,
 0.06667930003727127,
 0.03548896792772829,
 0.014235477453700298,
 0.08540541355898731,
 0.025357598270650872,
 0.07456450125755552,
 0.14158173917618372,
 0.03469366586332758,
 0.00981493626309466,
 0.040888124390

In [183]:
r_rand

Quantum object: dims = [[15], [15]], shape = (15, 15), type = oper, isherm = True
Qobj data =
[[ 3.62608849e-01-1.05980236e-16j  9.03043504e-02+1.04185927e-01j
  -4.49484625e-02+6.40648297e-03j -3.18778406e-02-9.24628170e-02j
   4.83871646e-02-7.02121904e-02j  1.04275840e-01+2.20103205e-02j
   9.82048793e-02+8.38123425e-02j  3.03262056e-02+9.40419374e-02j
  -3.83765434e-02+8.40869425e-02j -6.00442977e-02+6.10055282e-02j
  -5.05210816e-02+8.02485010e-03j -3.40084354e-02-3.10074715e-02j
  -9.96493113e-03-1.67103524e-02j  2.97906342e-03-1.32747547e-02j
  -3.70452102e-03-2.16098897e-02j]
 [ 9.03043504e-02-1.04185927e-01j  1.15757807e-01-6.60366235e-17j
   5.96207834e-02+6.88761829e-03j -3.72791508e-02-4.74329664e-02j
  -4.43165349e-02-3.84496822e-02j  1.90498986e-03-4.59792134e-04j
   6.39880069e-02-2.28590082e-04j  5.69366305e-02-2.28428227e-02j
   7.52077120e-03+6.05985176e-03j -8.33488897e-03+6.20828527e-02j
  -3.14627210e-04+2.64780906e-02j -6.12846900e-03-2.29604743e-02j
  -6.10985204

In [184]:
r_est = v2r(np.linalg.pinv(E)@p)
r_est

Quantum object: dims = [[15], [15]], shape = (15, 15), type = oper, isherm = True
Qobj data =
[[ 0.10412235+9.42167040e-18j  0.02391765+4.14962740e-02j
  -0.00728839+1.28478362e-02j  0.00557723-2.92301971e-02j
   0.00378968+5.26435483e-03j  0.02496239+2.08521546e-02j
   0.03662599+3.64630250e-02j  0.01934217+4.47602125e-02j
   0.00097222+4.84017598e-02j  0.01483178+3.50231355e-03j
   0.02561465-5.52380993e-03j -0.0356276 -2.70588664e-02j
  -0.0450809 -2.12951888e-02j  0.01403442-3.01382110e-03j
   0.02794103+1.59957687e-02j]
 [ 0.02391765-4.14962740e-02j  0.10159505+1.02245356e-17j
   0.02440408-1.33465954e-02j -0.00913654-6.40813822e-03j
   0.00326783-2.07320796e-02j  0.01549804-4.54543158e-03j
   0.05070638-1.00877068e-02j  0.06516521-1.64017411e-02j
   0.01726467+2.05569769e-02j -0.0026693 +1.80445296e-02j
  -0.00024189+1.35559880e-02j  0.01049841-5.46018993e-03j
  -0.00018794+1.22073670e-02j -0.01529502+1.34289386e-02j
  -0.00964671-2.07454052e-02j]
 [-0.00728839-1.28478362e-02j  0

In [190]:
fidelity(mle, r_rand)

0.7260248498876916

In [188]:
mle = PSD_rho(r_est/r_est.tr())

In [189]:
mle

Quantum object: dims = [[15], [15]], shape = (15, 15), type = oper, isherm = True
Qobj data =
[[ 0.13538452+0.j          0.02326205+0.05189893j -0.00324021+0.01802352j
  -0.00257851-0.02465181j  0.00538248+0.00037457j  0.03003136+0.01896784j
   0.05268423+0.05341837j  0.02040058+0.04823011j -0.00313818+0.05018725j
   0.0042931 +0.00068713j  0.01824791-0.00391454j -0.02498472-0.01494056j
  -0.04218543-0.02470257j  0.00948451+0.0021304j   0.02473437+0.00788454j]
 [ 0.02326205-0.05189893j  0.10993077+0.j          0.02895133-0.01577594j
  -0.01473307-0.01373998j -0.00386148-0.0257922j   0.01910203-0.00268401j
   0.06637652-0.0128891j   0.08191634-0.0113546j   0.03089537+0.02747461j
  -0.0014989 +0.01731529j -0.0030243 +0.00887468j -0.00225078-0.00667771j
  -0.00019646+0.01347127j -0.01479962+0.01283562j -0.01413913-0.0266876j ]
 [-0.00324021-0.01802352j  0.02895133+0.01577594j  0.10310918+0.j
   0.01072212-0.02720222j -0.01868166-0.00790617j -0.00887436-0.00942714j
  -0.0133397 +0.00364576